Newsletter 2 go
pimcore/customer-data-framework pull request #131
Opened 2019-09-25 12:35 UTC by ultramegatom

Add new newsletter provider: Newsletter2Go: https://www.newsletter2go.com/

2019-10-01 11:56 UTC, fashxp requested changes

2019-10-01 11:56 UTC, fashxp commented on src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
> +        $this->registerAuthServerConfiguration($container, $config['oauth_server']);
is this really newsletter2go related?

2019-10-01 11:56 UTC, fashxp commented on src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
> +    private function registerAuthServerConfiguration(ContainerBuilder $container, array $config)
is this really newsletter2go related?

2019-10-01 11:56 UTC, fashxp commented on src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
> +    public function prepend(ContainerBuilder $container)
is this really newsletter2go related?

2019-10-01 11:56 UTC, fashxp commented on src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
> +class PimcoreCustomerManagementFrameworkExtension extends ConfigurableExtension implements PrependExtensionInterface
is this really newsletter2go related?

2019-10-01 11:56 UTC, fashxp commented on src/Newsletter/ProviderHandler/Newsletter2Go.php
> +    public function __construct($shortcut, $listId, $doubleOptInFormCode, array $statusMapping = [], array $reverseStatusMapping = [], array $mergeFieldMapping = [], array $fieldTransformers = [], Ne
param with no default value after params with default values ... does not make any sense

2024-03-22 07:57 UTC, markus-moser commented
As there was no update of this PR since the last 5 years it's outdated and therefore I'll close it.

2024-03-22 07:57 UTC, closed without merging