Move custom reports config to prepend extension
pimcore/customer-data-framework pull request #404
Opened 2023-01-23 12:21 UTC by dvesh3

Resolves #398

2023-01-30 12:09 UTC, kingjia90 requested changes
LGTM, just some minor feedback

2023-01-30 12:09 UTC, kingjia90 commented on src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
> +        } elseif (Version::getMajorVersion() < 11) { //@TODO BC layer for Pimcore 10
```suggestion
        } elseif (Version::getMajorVersion() < 11) { //@TODO remove BC layer when dropping support for Pimcore 10
```

2023-01-30 12:09 UTC, kingjia90 commented on src/DependencyInjection/PimcoreCustomerManagementFrameworkExtension.php
> +            $loader->load('custom_reports.yml');
```suggestion
            $loader->load('custom_reports.yaml');
```
just wondering, should we start recommending `yaml` for 11 related stuff?

2023-01-30 12:09 UTC, kingjia90 commented on src/Resources/config/custom_reports_legacy.yml
> +      - 'CustomerManagementFrameworkBundle\CustomReport\Adapter\TermSegmentBuilder'
```suggestion
          - 'CustomerManagementFrameworkBundle\CustomReport\Adapter\TermSegmentBuilder'
```

2023-01-30 12:09 UTC, kingjia90 commented on src/CustomReport/Adapter/TermSegmentBuilderBase.php
> +//@TODO BC layer for Pimcore 10
```suggestion
//@TODO remove BC layer when dropping support for Pimcore 10
```

2023-01-30 22:49 UTC, kingjia90 commented
https://github.com/pimcore/customer-data-framework/blob/15146baf4efabc470804e8d218d6166d5439b537/src/Resources/public/js/pimcore/report/custom/definitions/termSegmentBuilder.js#L15-L16

needs to be changed to `pimcore.bundle.customreports.custom.definition.termSegmentBuilder` or it won't appear in the Source Definition list

2023-01-31 11:11 UTC, dvesh3 commented
> https://github.com/pimcore/customer-data-framework/blob/15146baf4efabc470804e8d218d6166d5439b537/src/Resources/public/js/pimcore/report/custom/definitions/termSegmentBuilder.js#L15-L16
> 
> In 11, it needs to be changed to `pimcore.bundle.customreports.custom.definition.termSegmentBuilder` or it won't appear in the [Source Definition list](https://github.com/pimcore/pimcore/pull/13920/files?w=1#diff-fcf58cd506dd39ccc7be87256a1a204433e2fa462dfcb9517f8e5c1bfff83164L780). eg. [analytics](https://github.com/pimcore/pimcore/pull/13920/files?w=1#diff-d3f6942a34843d69fa64b207d286ad004b4daa1deff53a01322932c06f649d02) The rest looks fine to me.

Done

2023-01-31 12:04 UTC, kingjia90 approved these changes

2023-01-31 12:04 UTC, merged