Activity List class incompatibility fix with return type
pimcore/customer-data-framework pull request #434
Opened 2023-03-20 08:39 UTC by aryaantony92

Resolves #423

2023-03-20 08:43 UTC, aryaantony92 commented
Tests would be fixed by #432

2023-03-21 06:59 UTC, martineiber requested changes
#432 is merged. 
Please rebase your branch to fix the failing stan tests.

2023-03-21 06:59 UTC, martineiber commented on src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
> +        return $this;
When we use the setModel from DaoInterface, then we should to a right implementation and also set the model?

```suggestion
        $this->model = $model;
        
        return $this;
```

2023-03-21 12:03 UTC, aryaantony92 commented on src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
> +        return $this;
Yes 👍

2023-03-21 12:09 UTC, martineiber commented
@aryaantony92 
I was just thinking if we should add the interface to the MariaDbDao.php as well?
https://github.com/pimcore/customer-data-framework/blob/99da5e523e8435bed005c18304bc936c129c3de0/src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php#L23

2023-04-05 11:19 UTC, martineiber requested changes

2023-04-05 11:19 UTC, martineiber commented on phpstan-baseline.neon
> +		    message: "#^Property CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList\\\\MySqlDao::$model (CustomerManagementFrameworkBundle\Model\ActivityList\MySqlActi
This should fix the stan error. 
```suggestion
		    message: "#^Property CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList\\\\MySqlDao::$model (CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\MySqlActivityList) does not accept Pimcore\\\\Model\\\\AbstractModel.$#"
```

2023-04-05 11:29 UTC, martineiber requested changes
let's try this change :D

2023-04-05 11:29 UTC, martineiber commented on phpstan-baseline.neon
> +		    message: "#^Property CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList\\\\MySqlDao::$model (CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\
```suggestion
		    message: "#^Property CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList\\\\MySqlDao\\:\\:$model (CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\MySqlActivityList) does not accept Pimcore\\\\Model\\\\AbstractModel.$#"
```

2023-04-05 11:29 UTC, martineiber commented on phpstan-baseline.neon
> +		    message: "#^Property CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList\\\\MariaDbDao::$model (CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\
```suggestion
		    message: "#^Property CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList\\\\MariaDbDao\\:\\:$model (CustomerManagementFrameworkBundle\\\\Model\\\\ActivityList\\\\DefaultMariaDbActivityList) does not accept Pimcore\\\\Model\\\\AbstractModel.$#"
```

2023-04-05 11:38 UTC, blankse commented
You know you can create the baseline file via "-b" option?
https://phpstan.org/user-guide/command-line-usage#--generate-baseline%7C-b

2023-04-05 11:44 UTC, martineiber commented
> You know you can create the baseline file via "-b" option? https://phpstan.org/user-guide/command-line-usage#--generate-baseline%7C-b

Didn't know that, thanks for the info :)

2023-04-07 10:21 UTC, martineiber commented
Waiting for https://github.com/pimcore/customer-data-framework/pull/447

2023-04-07 11:32 UTC, martineiber approved these changes

2023-04-07 11:33 UTC, merged